[package]
name = "pmhelp-internal"
version = "0.0.1"
edition = "2018"
description = "Internals that will be used by `pmhelp`. This should not be used directly."

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"
